### ISSUE TITLE
Atari Lynx (LNX) set is missing

### ISSUE THREAD

**Issue by foxp4v** [proper1g1r/proper1g1r-collection#2]
As title says, the set for more common file format .LNX for Atari Lynx is missing. Thank you for attenction.

**Comment by proper1g1r** [comment]
Yup, this is already documented [here](https://github.com/proper1g1r/proper1g1r-collection?tab=readme-ov-file#systems-with-an-empty-dat-file-from-dat-o-matic). Unfortunately the DAT file for .LNX is lacking — if you generate it [here](https://datomatic.no-intro.org/index.php?page=manager&s=30&download=1874) for the .LNX format with default options, you'll see it'll only have 5 entries (vs 115 entries for .LYX). If you filter out beta and unreleased games, the DAT is empty.

Not sure why that's the case since it's actually not hard to find .LNX ROMs, but this collection follows the DAT files so I had to keep .LNX out. You can build it yourself based on the .LYX set, though, since the games are the same.
